### ISSUE TITLE
Integrating with Rails app

### ISSUE THREAD

**Issue by tgoldenberg** [mariopeixoto/react-bootstrap-rails#1]
@mariopeixoto  Getting this error after following the instructions on the README: 

Permission denied - /Library/Ruby/Gems/2.0.0/gems/react-bootstrap-rails-0.13.0/vendor/assets/javascripts/react_bootstrap.js

Suggestions???

 -tgoldenberg

**Comment by mariopeixoto** [comment]
@tgoldenberg Hi, Sorry for the delay, I wasn't getting notification emails from this repo.

It doesn't seem to be an error originated from the gem itself.

Assuming you still have the issue, could you elaborate on your ruby environment?
Are you using RVM and gemsets? Did you install the gem using a sudo or the root user?

Sorry again.

**Comment by mariopeixoto** [comment]
Closing it.
