### ISSUE TITLE
 Unknown transformer transformerName specified in optional

### ISSUE THREAD

**Issue by MincePie** [mariopeixoto/react-bootstrap-rails#12]
I added this gem to my gem file (in addition to bootstrap-sass), so gem file currently has these bootstrap files:

[](gem)

I updated my application.js so that it now has:

[//= require jQuery
//= require jquery_ujs
//= require tether
//= require bootstrap-sprockets
//= require turbo links
//= require react
//= require react_ujs
//= require react_bootstrap
//= require components
//= require_tree .
](url)

When I save all of this and try to reload a page that was previously rendering, I get this error:

ExecJS::ProgramError at /app_roles
ReferenceError: Unknown transformer transformerName specified in optional

The app_role.es6.jsx file has:

[class AppRole extends React.Component {
  render () {
    return (
      <div>
        <div>Title: {this.props.title}</div>
        <div>Display Name: {this.props.displayName}</div>
        <div>Category: {this.props.category}</div>
      </div>
    );
  }
}

AppRole.propTypes = {
  title: React.PropTypes.string,
  displayName: React.PropTypes.string,
  category: React.PropTypes.node
};
](url)

Is there something else I need to do to be able to use bootstrap with react?

Thank you

**Comment by mariopeixoto** [comment]
This gem is not maintained anymore. Sorry about that.
