### ISSUE TITLE
Uncaught TypeError: Cannot read property 'propTypes' 

### ISSUE THREAD

**Issue by travisdmathis** [mariopeixoto/react-bootstrap-rails#9]
when adding react-bootstrap-rails to a rails project I get this error.. When trying to use ReactBootstrap i am told the global var doesn't exist...

i'm using react-rails + react-bootstrap-rails

**Comment by travisdmathis** [comment]
anyone maintaining this anymore?

**Comment by mariopeixoto** [comment]
In the asset pipeline you have to require the react-bootstrap before your scripts, otherwise it won't be able to access the global var.
